appName: nginx

replicaCount: 3

image:
  repository: 250738637992.dkr.ecr.eu-west-1.amazonaws.com/x23186925-thesis
  tag: latest
  pullPolicy: IfNotPresent

containerPort: 8000

imagePullSecrets: ecr-secret

service:
  type: NodePort
  port: 80
  nodePort: 30009

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

serviceAccount:
  create: true
  name: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - /
  tls: []
