apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "nginx-app.fullname" . }}-network-policy
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.appName }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}  # Adjust according to your requirements
  egress:
  - to:
    - podSelector: {}  # Adjust according to your requirements
